FROM golang AS builder

WORKDIR /go/src

COPY ./rocks_app /go/src/
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM alpine:2.6  
WORKDIR /root/
COPY --from=builder /go/src ./

RUN rm go.mod && rm rocks.go

CMD ["./app"]  